[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (built assets)
  publish = "dist"
  
  # Directory with the serverless functions
  functions = "netlify/functions"

[build.environment]
  # Node version for builds
  NODE_VERSION = "18"
  
  # Skip Husky install in CI
  HUSKY_SKIP_INSTALL = "1"
  
  # API URL for production backend on Railway
  VITE_API_URL = "https://consensusai-production.up.railway.app"

# Redirects are now handled by /public/_redirects file for better compatibility

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers for static assets (caching)
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for API requests
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# API requests handled by frontend code, not redirects

# Form handling (if you plan to use Netlify Forms)
[[headers]]
  for = "/forms/*"
  [headers.values]
    X-Robots-Tag = "noindex" 