[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd backend && npm ci --only=production']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production'
PORT = '3000'
RAILWAY_CORS_ORIGIN = 'https://consensusai.netlify.app,https://consensus-ai.netlify.app,https://main--consensusai.netlify.app'