[build]
builder = "nixpacks"

[build.nixpacks]
installCmd = "npm install && npm install --prefix backend"
buildCmd = "echo 'No build needed'"
startCmd = "npm start"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
RAILWAY_STATIC_URL = ""
# Force Railway to not override CORS headers
RAILWAY_CORS_OVERRIDE = "false"